name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche l'action lors d'un push sur main
  pull_request:
    branches:
      - main  # Déclenche l'action lors d'une PR vers main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilise Ubuntu comme environnement

    steps:
    # 1️⃣ Récupération du code source
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Configuration de Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3️⃣ Connexion à Docker Hub ou GitHub Container Registry (GHCR)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # 🔴 À configurer dans GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4️⃣ Cache Docker pour accélérer les builds
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # 5️⃣ Build & Push des images Docker pour service_a et service_b
    - name: Build & Push Docker image for service_a
      uses: docker/build-push-action@v5
      with:
        context: ./service_a
        file: ./service_a/Dockerfile
        push: true  # On pousse l'image après build
        tags: user_name/service_a:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build & Push Docker image for service_b
      uses: docker/build-push-action@v5
      with:
        context: ./service_b
        file: ./service_b/Dockerfile
        push: true
        tags: user_name/service_b:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # 6️⃣ Lancement des tests avec Docker Compose
    - name: Run tests
      run: |
        docker-compose up -d --wait  # Assure que les services sont bien démarrés
        docker-compose exec service_a pytest || exit 1  # Exécute les tests avec pytest
        docker-compose down  # Nettoyage des services après tests

    # 7️⃣ Déploiement en production (si nécessaire)
    - name: Deploy to production
      run: |
        ssh user@your_server <<EOF
          docker pull user_name/service_a:latest
          docker pull user_name/service_b:latest
          docker-compose up -d --remove-orphans
        EOF
