name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image for service_a
      run: docker build ./service_a --file ./service_a/Dockerfile --tag service_a:$(date +%s)

    - name: Build Docker image for service_b
      run: docker build ./service_b --file ./service_b/Dockerfile --tag service_b:$(date +%s)
